version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gestalt-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # For file watching on Windows
    networks:
      - gestalt-network

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestalt-prod
    ports:
      - "8080:80"
    networks:
      - gestalt-network
networks:
  gestalt-network:
    driver: bridge